### ISSUE TITLE
Add Postal Code to Database as Own Field in Addition to Existing Address Field

### ISSUE THREAD

**Issue by mekkim** [mekkim/donatemask#51]
Currently (thanks @JessEBuchanan!) the various fields for the address are collected from the request form and then assembled into a single address field and pushed into the database.  Please add an additional push, as its own database entry, of just the postal code alone.  That way each database request entry will have both "address" (full, including postal code) and "postal code" (just postal code) fields.  

The reasoning is that for the purposes of the privacy policy, after we ship out the masks, there is no "legitimate purpose" to keep the full address, so it is appropriate to delete it per data retention and destruction terms.  However, we want to preserve the postal code, which is not personally identifiable, for statistical analysis purposes.  In this manner, rather than having to extract the postal code from the full address manually when deleting the address, we can just have the whole address field be deleted and the postal code field kept.  Later, a trigger can be written for "when fulfilled is set to true, delete address field".  It also makes it easier to query the retention policy period for the address field as non-blank addresses can be tracked based on time since creation, etc.  It further makes it easier to do statistical analysis based on postal code without having to re-parse it out from the address field at analysis time.

**Comment by mekkim** [comment]
Hey @Sync271. It looks like the above github-action bot may have been an unintentional side effect of adjusting the tree structure?

**Comment by Sync271** [comment]
> Hey @Sync271. It looks like the above github-action bot may have been an unintentional side effect of adjusting the tree structure? 

Will look into it soon!

**Comment by Sync271** [comment]
@mekkim , so I know what's causing the issue but I am not on my computer now so can't really fix it. The problem is this file: https://github.com/mekkim/donatemask/blob/main/.github/workflows/main.yml

You could either delete it entirely or modify it to our needs, I'll leave that for you to decide. Anyways, that file specifies an "issue structure/pattern" that needs to be followed for every issue opened and that's the reason it threw an error.

**Comment by mekkim** [comment]
I've changed the main.yml file to main.ymlDISABLED.  That should prevent it from executing (I hope!) Reopening issue.

**Comment by JessEBuchanan** [comment]
I should be able to do this before the weekend. Though just wondering if something will need to be changed on the database end to accept a new field? Or is it flexible enough to have the new requests have the new separate postal code field?

**Comment by mekkim** [comment]
We did this previously when we added the "fulfilled" field.  All the new entries were created with the extra field and the previous entries had to be manually updated, which is fine for this case too.

**Comment by JessEBuchanan** [comment]
I added the new field in he newMaskRequest, merged to main.  

I can start with going through the fulfilled requests in the database and adding the postal code field. For unfulfilled requests, can we add the postal code field as they are fulfilled, if I can't get to them before then? 

I was also looking at some of the MongoDB documentation, there are things called triggers. Since we need to delete the identifying data once requests go out, would it be a good idea to set up a trigger for when requestFulfilled changes to true to delete all the field data except for postal code, timestamp and # of masks?

**Comment by mekkim** [comment]
Great work!  Sarah can help with going through the previous requests and adding the field as she has direct access to the DB as well.  Ping her on Slack to coordinate.  

If you want to set up a trigger, sure!  That's great!

**Comment by mekkim** [comment]
Resolved by #72
