### ISSUE TITLE
Summary Page Crashes on Reload

### ISSUE THREAD

**Issue by Sync271** [mekkim/donatemask#93]
### Steps to Reproduce
1) Got to <https://donatemask.ca/>
2) Navigate to Summary Page
![image](https://user-images.githubusercontent.com/67158080/167251189-7abc3238-2f11-41e8-846a-972d4ffee436.png)
3) Reload the page and it crashes
![image](https://user-images.githubusercontent.com/67158080/167251199-26f5ce80-6f1b-4d74-8ddc-5c07c22b788d.png)

### Possible Cause/Solution
- in https://github.com/mekkim/donatemask/pull/92, it's mentioned that `npm install` has to be run before creating the build to include swr. Not sure if it was done or not.

**Comment by Sync271** [comment]
CC @mekkim @humphd

**Comment by humphd** [comment]
Nice catch @Sync271. Looking at the server, the `/home/donatemask/donatemask.ca/node_modules/` folder doesn't contain `stripe`, which make sense with the error above.  I also see a `node_modulesOLD/` folder which *does* contain it.  I wonder if your package-lock.json wasn't in sync (running `npm install` rewrites it).

So I'd say you need to run `npm install` to get the proper dependencies for the server.

@mekkim this would be an interesting time to test the steps for #88.  Since the server is crashed, you can see if this will bring it back up. In theory, you should be able to do:

```sh
$ cd ~
$ npm install
$ passenger-config restart-app --ignore-app-not-running --ignore-passenger-not-running .
```

If that works, we can automate it.

**Comment by Sync271** [comment]
@humphd I also tried running it locally and ran into a similar issue. I see only "..." as placeholder instead of actual numbers. Not quite sure what's causing the issue.

**Comment by humphd** [comment]
@Sync271 that's due to the production server being down, and the current front-end code always using the production URL (this needs to get fixed in a follow-up as well).  You can try running `npm test` locally to make sure the routes are actually working.

The fix for this is to get `stripe` added back to the dependencies in `node_modules`.

**Comment by Sync271** [comment]
Ah yes!
That makes sense, I'm a moron 😅.

**Comment by humphd** [comment]
I filed https://github.com/mekkim/donatemask/issues/94 to deal with the problem of running this locally. You're not a moron, I had the same thing happen to me while debugging last week :). It's not obvious that it would do this.

**Comment by mekkim** [comment]
Thanks for catching, friends.  I did run `npm install` and uploaded the newly created `node_module` folder (and renamed the old one).  Not sure why some of the dependencies were missing given that.

**Comment by mekkim** [comment]
Maybe it has to do with the lock file sync issues mentioned?

**Comment by mekkim** [comment]
If I merge the old node_modules into the new, will that address the issue for the moment without clobbering anything?

**Comment by mekkim** [comment]
> Ah yes! That makes sense, I'm a moron 😅.

You're DEFINITELY not a moron. I got caught with this too. And I think @JessEBuchanan did while testing also. It's not obvious. :)

**Comment by mekkim** [comment]
I merged the old and the new node_modules, overwriting if newer, and it seems to be fine now.  Please let me know if the issue reoccurs?
